name: Kopier Action
author: Bjerk AS
description: Github Actions to help share information across many repositories
branding:
  icon: copy
  color: purple
inputs:
    github-token:
        description: Github Token
        default: ${{ github.token }}
        required: true
    files:
        description: Files to import. e.g. templates/**
        required: false
    github-search:
        description: Search for repositories instead of implictly set them (e.g. «org:bjerkio topic:infra»)
        required: false
    repos:
        description: Repositories to push changes to
        required: true
    base-path:
        description: Only add files in a spesific folder, e.g. .github/workflows
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'
