name: Kopier Action
author: Bjerk AS
description: Helps manage multiple repositories.
branding:
  icon: copy
  color: purple
inputs:
  github-token:
    description: Github Token
    default: ${{ github.token }}
    required: true

  repos:
    description: List of repositories to add files to.
    required: false

  base-path:
    description: Only add files in a spesific folder, e.g. templates/infra-code
    required: true
    default: templates/

  commit-message:
    description: Commit message.
    required: true
    default: "chore(kopier): {{commit.subject}}"

  title:
    description: Pull Request title
    required: true
    default: "chore(kopier): {{commit.subject}}"

  body:
    description: Pull Request body
    required: false

  query:
    description: Search for repositories instead of implictly set them (e.g. «org:bjerkio topic:infra»)
    required: false

  head:
    description: A branch name for updates.
    required: false

  base:
    description: Base branch is where the pull request is opened. Defaults to default branch.
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
