on:
  push:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          repos: |
            bjerkio/kopier-example
          github-token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          files: example/templates/**
