name: Packaging
on:
  push:
    branches:
      - main

jobs:
  update-dist-and-release:
    name: Update dist files and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: dist/**
          commit_message: 'chore(dist): Update dist [automated commit]'
          commit_user_name: Bjerk Bot
          commit_user_email: bjerk-bot@users.noreply.github.com
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          release-type: node
      - name: tag major and patch versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name bjerk-bot
          git config user.email bjerk-bot@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.BJERKBOT_GITHUB_TOKEN }}@github.com/bjerkio/kopier.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
